export const ICONS = [
    {
        labelKey: "category.food_dining",
        icons: [
            { name: "food", className: "icon-[mdi--food]" },
            { name: "food-apple", className: "icon-[mdi--food-apple]" },
            {
                name: "food-fork-drink",
                className: "icon-[mdi--food-fork-drink]",
            },
            {
                name: "silverware-fork-knife",
                className: "icon-[mdi--silverware-fork-knife]",
            },
            { name: "cup", className: "icon-[mdi--cup]" },
            { name: "coffee", className: "icon-[mdi--coffee]" },
            { name: "glass-wine", className: "icon-[mdi--glass-wine]" },
            { name: "breakfast", className: "icon-[mdi--bread-slice]" },
            { name: "launch", className: "icon-[mdi--meat]" },
            { name: "dinner", className: "icon-[mdi--food-turkey]" },
            { name: "snack", className: "icon-[mdi--treat]" },
            { name: "treat", className: "icon-[mdi--food-ramen]" },
            { name: "drinks", className: "icon-[mdi--local-bar]" },
        ],
    },
    {
        labelKey: "category.transport_travel",
        icons: [
            { name: "car", className: "icon-[mdi--car]" },
            { name: "car-electric", className: "icon-[mdi--car-electric]" },
            { name: "bus", className: "icon-[mdi--bus]" },
            { name: "train", className: "icon-[mdi--train]" },
            { name: "subway", className: "icon-[mdi--subway]" },
            { name: "bike", className: "icon-[mdi--bike]" },
            { name: "airplane", className: "icon-[mdi--airplane]" },
            { name: "map", className: "icon-[mdi--map]" },
            { name: "map-marker", className: "icon-[mdi--map-marker]" },
            { name: "compass", className: "icon-[mdi--compass]" },
            { name: "ticket", className: "icon-[mdi--ticket]" },
            { name: "transport", className: "icon-[mdi--transportation]" },
            { name: "taxi", className: "icon-[mdi--taxi]" },
            { name: "parking", className: "icon-[mdi--parking]" },
            // icon-[mdi--gas-station] 已在 Housing & Utilities 中保留
            { name: "travel", className: "icon-[mdi--bag-suitcase]" },
        ],
    },
    {
        labelKey: "category.shopping_goods",
        icons: [
            { name: "cart", className: "icon-[mdi--cart]" },
            { name: "cart-outline", className: "icon-[mdi--cart-outline]" },
            { name: "cart-plus", className: "icon-[mdi--cart-plus]" },
            { name: "basket", className: "icon-[mdi--basket]" },
            { name: "store", className: "icon-[mdi--store]" },
            { name: "storefront", className: "icon-[mdi--storefront]" },
            { name: "bag-personal", className: "icon-[mdi--bag-personal]" },
            { name: "shopping", className: "icon-[mdi--shopping-cart]" },
            { name: "household", className: "icon-[mdi--house-add]" },
            { name: "electronics", className: "icon-[mdi--tablet-cellphone]" },
            { name: "credits", className: "icon-[mdi--bitcoin]" },
            { name: "baby-and-mom", className: "icon-[mdi--baby-face]" },
            { name: "accessories", className: "icon-[mdi--watch]" },
            { name: "office", className: "icon-[mdi--briefcase]" },
        ],
    },
    {
        labelKey: "category.apparel_beauty",
        icons: [
            { name: "tshirt-crew", className: "icon-[mdi--tshirt-crew]" },
            { name: "shoe-sneaker", className: "icon-[mdi--shoe-sneaker]" },
            { name: "hanger", className: "icon-[mdi--hanger]" },
            { name: "lipstick", className: "icon-[mdi--lipstick]" },
            { name: "sunglasses", className: "icon-[mdi--sunglasses]" },
        ],
    },
    {
        labelKey: "category.housing_utilities",
        icons: [
            { name: "home", className: "icon-[mdi--home]" },
            { name: "home-outline", className: "icon-[mdi--home-outline]" },
            { name: "lightbulb", className: "icon-[mdi--lightbulb]" },
            { name: "water", className: "icon-[mdi--water]" },
            { name: "gas-station", className: "icon-[mdi--gas-station]" },
            { name: "flash", className: "icon-[mdi--flash]" },
            { name: "housing", className: "icon-[mdi--house-city]" },
            {
                name: "electricity",
                className: "icon-[mdi--battery-charging-10]",
            },
            { name: "mgmt-fee", className: "icon-[mdi--gardening]" },
            { name: "rent", className: "icon-[mdi--hoop-house]" },
            { name: "mortgage", className: "icon-[mdi--house-floor-l]" },
            { name: "cleaning", className: "icon-[mdi--vacuum-cleaner]" },
            { name: "renovation", className: "icon-[mdi--house-flood]" },
        ],
    },
    {
        labelKey: "category.comm_internet",
        icons: [
            { name: "cellphone", className: "icon-[mdi--cellphone]" },
            { name: "wifi", className: "icon-[mdi--wifi]" },
            { name: "router", className: "icon-[mdi--router]" },
            { name: "server", className: "icon-[mdi--server]" },
            { name: "earth", className: "icon-[mdi--earth]" },
            { name: "phone", className: "icon-[mdi--phone]" },
        ],
    },
    {
        labelKey: "category.medical_health",
        icons: [
            { name: "heart", className: "icon-[mdi--heart]" },
            { name: "hospital", className: "icon-[mdi--hospital]" },
            { name: "pill", className: "icon-[mdi--pill]" },
            { name: "stethoscope", className: "icon-[mdi--stethoscope]" },
            { name: "medical-bag", className: "icon-[mdi--medical-bag]" },
            { name: "medical", className: "icon-[mdi--hospital-box]" },
            { name: "clinic", className: "icon-[mdi--stethoscope]" },
            { name: "pharmacy", className: "icon-[mdi--pill-multiple]" },
            // icon-[mdi--account-heart] 已在 Charity & Donations 中保留
        ],
    },
    {
        labelKey: "category.education_learning",
        icons: [
            { name: "book", className: "icon-[mdi--book]" },
            { name: "book-open", className: "icon-[mdi--book-open]" },
            { name: "school", className: "icon-[mdi--school]" },
            { name: "graduation-cap", className: "icon-[mdi--graduation-cap]" },
            { name: "education", className: "icon-[mdi--academic-cap]" },
            { name: "tuition", className: "icon-[mdi--account-school]" },
            { name: "books", className: "icon-[mdi--book-open-blank-variant]" },
            { name: "courses", className: "icon-[mdi--book-account]" },
        ],
    },
    {
        labelKey: "category.entertainment_leisure",
        icons: [
            { name: "camera", className: "icon-[mdi--camera]" },
            { name: "movie", className: "icon-[mdi--movie]" },
            { name: "music", className: "icon-[mdi--music]" },
            { name: "guitar", className: "icon-[mdi--guitar-acoustic]" },
            { name: "gamepad", className: "icon-[mdi--gamepad]" },
            { name: "dice-multiple", className: "icon-[mdi--dice-multiple]" },
            { name: "entertainment", className: "icon-[mdi--google-gamepad]" },
            { name: "movies", className: "icon-[mdi--local-movies]" },
            { name: "fitness", className: "icon-[mdi--fitness-center]" },
            { name: "wellness", className: "icon-[mdi--emoticon]" },
            { name: "shows", className: "icon-[mdi--microphone-variant]" },
        ],
    },
    {
        labelKey: "category.pets",
        icons: [
            { name: "dog", className: "icon-[mdi--dog]" },
            { name: "cat", className: "icon-[mdi--cat]" },
            { name: "paw", className: "icon-[mdi--paw]" },
            { name: "fish", className: "icon-[mdi--fish]" },
            { name: "pets", className: "icon-[mdi--pets]" },
        ],
    },
    {
        labelKey: "category.social_gifts",
        icons: [
            { name: "gift", className: "icon-[mdi--gift]" },
            { name: "balloon", className: "icon-[mdi--balloon]" },
            { name: "party-popper", className: "icon-[mdi--party-popper]" },
            { name: "social", className: "icon-[mdi--party-balloon]" },
            { name: "family", className: "icon-[mdi--elderly]" },
            { name: "loan", className: "icon-[mdi--hand-back-right]" },
            { name: "hongbao", className: "icon-[mdi--redeem]" },
            { name: "Lean", className: "icon-[mdi--hand-extended]" },
        ],
    },
    {
        labelKey: "category.finance_wealth",
        icons: [
            { name: "wallet", className: "icon-[mdi--wallet]" },
            { name: "bank", className: "icon-[mdi--bank]" },
            { name: "cash", className: "icon-[mdi--cash]" },
            { name: "currency-usd", className: "icon-[mdi--currency-usd]" },
            { name: "currency-eur", className: "icon-[mdi--currency-eur]" },
            { name: "piggy-bank", className: "icon-[mdi--piggy-bank]" },
            { name: "chart-line", className: "icon-[mdi--chart-line]" },
            { name: "chart-pie", className: "icon-[mdi--chart-pie]" },
            { name: "shield", className: "icon-[mdi--shield]" },
            { name: "shield-check", className: "icon-[mdi--shield-check]" },
            { name: "security", className: "icon-[mdi--security]" },
            { name: "credit-card", className: "icon-[mdi--credit-card]" },
            {
                name: "credit-card-check",
                className: "icon-[mdi--credit-card-check]",
            },
            {
                name: "card-account-details",
                className: "icon-[mdi--card-account-details]",
            },
            { name: "wage", className: "icon-[mdi--credit-card-outline]" },
            { name: "part-time", className: "icon-[mdi--google-cardboard]" },
            { name: "fees-and-charges", className: "icon-[mdi--cash-minus]" },
            {
                name: "reconciliation",
                className: "icon-[mdi--credit-card-sync-outline]",
            },
            { name: "refund", className: "icon-[mdi--credit-card-refund]" },
            { name: "drawback", className: "icon-[mdi--recurring-payment]" },
        ],
    },
    {
        labelKey: "category.charity_donations",
        icons: [
            { name: "hand-heart", className: "icon-[mdi--hand-heart]" },
            { name: "hand-coin", className: "icon-[mdi--hand-coin]" },
            { name: "account-heart", className: "icon-[mdi--account-heart]" },
            { name: "charity", className: "icon-[mdi--charity]" },
        ],
    },
    {
        labelKey: "category.others",
        icons: [
            {
                name: "dots-horizontal",
                className: "icon-[mdi--dots-horizontal]",
            },
            { name: "help-circle", className: "icon-[mdi--help-circle]" },
            { name: "question-mark", className: "icon-[mdi--question-mark]" },
            {
                name: "other-expenses",
                className: "icon-[mdi--bookmark-multiple]",
            },
        ],
    },
];
