export const ICONS = {
	"Food & Drink": [
		{ name: "food", className: "icon-[mdi--food]" },
		{ name: "food-apple", className: "icon-[mdi--food-apple]" },
		{ name: "food-fork-drink", className: "icon-[mdi--food-fork-drink]" },
		{
			name: "silverware-fork-knife",
			className: "icon-[mdi--silverware-fork-knife]",
		},
		{ name: "cup", className: "icon-[mdi--cup]" },
		{ name: "coffee", className: "icon-[mdi--coffee]" },
		{ name: "glass-wine", className: "icon-[mdi--glass-wine]" },
	],
	Shopping: [
		{ name: "cart", className: "icon-[mdi--cart]" },
		{ name: "cart-outline", className: "icon-[mdi--cart-outline]" },
		{ name: "cart-plus", className: "icon-[mdi--cart-plus]" },
		{ name: "basket", className: "icon-[mdi--basket]" },
		{ name: "store", className: "icon-[mdi--store]" },
		{ name: "storefront", className: "icon-[mdi--storefront]" },
		{ name: "bag-personal", className: "icon-[mdi--bag-personal]" },
	],
	Transport: [
		{ name: "car", className: "icon-[mdi--car]" },
		{ name: "car-electric", className: "icon-[mdi--car-electric]" },
		{ name: "bus", className: "icon-[mdi--bus]" },
		{ name: "train", className: "icon-[mdi--train]" },
		{ name: "subway", className: "icon-[mdi--subway]" },
		{ name: "bike", className: "icon-[mdi--bike]" },
		{ name: "airplane", className: "icon-[mdi--airplane]" },
	],
	"Housing & Utilities": [
		{ name: "home", className: "icon-[mdi--home]" },
		{ name: "home-outline", className: "icon-[mdi--home-outline]" },
		{ name: "lightbulb", className: "icon-[mdi--lightbulb]" },
		{ name: "water", className: "icon-[mdi--water]" },
		{ name: "gas-station", className: "icon-[mdi--gas-station]" },
		{ name: "flash", className: "icon-[mdi--flash]" },
	],
	Communication: [
		{ name: "cellphone", className: "icon-[mdi--cellphone]" },
		{ name: "wifi", className: "icon-[mdi--wifi]" },
		{ name: "router", className: "icon-[mdi--router]" },
		{ name: "server", className: "icon-[mdi--server]" },
		{ name: "earth", className: "icon-[mdi--earth]" },
	],
	Health: [
		{ name: "heart", className: "icon-[mdi--heart]" },
		{ name: "hospital", className: "icon-[mdi--hospital]" },
		{ name: "pill", className: "icon-[mdi--pill]" },
		{ name: "stethoscope", className: "icon-[mdi--stethoscope]" },
		{ name: "medical-bag", className: "icon-[mdi--medical-bag]" },
	],
	Education: [
		{ name: "book", className: "icon-[mdi--book]" },
		{ name: "book-open", className: "icon-[mdi--book-open]" },
		{ name: "school", className: "icon-[mdi--school]" },
		{ name: "graduation-cap", className: "icon-[mdi--graduation-cap]" },
	],
	Entertainment: [
		{ name: "camera", className: "icon-[mdi--camera]" },
		{ name: "movie", className: "icon-[mdi--movie]" },
		{ name: "music", className: "icon-[mdi--music]" },
		{ name: "guitar", className: "icon-[mdi--guitar-acoustic]" },
		{ name: "gamepad", className: "icon-[mdi--gamepad]" },
		{ name: "dice-multiple", className: "icon-[mdi--dice-multiple]" },
	],
	Travel: [
		{ name: "map", className: "icon-[mdi--map]" },
		{ name: "map-marker", className: "icon-[mdi--map-marker]" },
		{ name: "ticket", className: "icon-[mdi--ticket]" },
		{ name: "compass", className: "icon-[mdi--compass]" },
	],
	"Clothing & Beauty": [
		{ name: "tshirt-crew", className: "icon-[mdi--tshirt-crew]" },
		{ name: "shoe-sneaker", className: "icon-[mdi--shoe-sneaker]" },
		{ name: "hanger", className: "icon-[mdi--hanger]" },
		{ name: "lipstick", className: "icon-[mdi--lipstick]" },
		{ name: "sunglasses", className: "icon-[mdi--sunglasses]" },
	],
	Pets: [
		{ name: "dog", className: "icon-[mdi--dog]" },
		{ name: "cat", className: "icon-[mdi--cat]" },
		{ name: "paw", className: "icon-[mdi--paw]" },
		{ name: "fish", className: "icon-[mdi--fish]" },
	],
	"Gifts & Holidays": [
		{ name: "gift", className: "icon-[mdi--gift]" },
		{ name: "balloon", className: "icon-[mdi--balloon]" },
		{ name: "party-popper", className: "icon-[mdi--party-popper]" },
	],
	Finance: [
		{ name: "wallet", className: "icon-[mdi--wallet]" },
		{ name: "bank", className: "icon-[mdi--bank]" },
		{ name: "cash", className: "icon-[mdi--cash]" },
		{ name: "currency-usd", className: "icon-[mdi--currency-usd]" },
		{ name: "currency-eur", className: "icon-[mdi--currency-eur]" },
		{ name: "piggy-bank", className: "icon-[mdi--piggy-bank]" },
		{ name: "chart-line", className: "icon-[mdi--chart-line]" },
		{ name: "chart-pie", className: "icon-[mdi--chart-pie]" },
	],
	Insurance: [
		{ name: "shield", className: "icon-[mdi--shield]" },
		{ name: "shield-check", className: "icon-[mdi--shield-check]" },
		{ name: "security", className: "icon-[mdi--security]" },
	],
	Subscriptions: [
		{ name: "credit-card", className: "icon-[mdi--credit-card]" },
		{ name: "credit-card-check", className: "icon-[mdi--credit-card-check]" },
		{
			name: "card-account-details",
			className: "icon-[mdi--card-account-details]",
		},
	],
	"Charity & Donations": [
		{ name: "hand-heart", className: "icon-[mdi--hand-heart]" },
		{ name: "hand-coin", className: "icon-[mdi--hand-coin]" },
		{ name: "account-heart", className: "icon-[mdi--account-heart]" },
	],
	Others: [
		{ name: "dots-horizontal", className: "icon-[mdi--dots-horizontal]" },
		{ name: "help-circle", className: "icon-[mdi--help-circle]" },
		{ name: "question-mark", className: "icon-[mdi--question-mark]" },
	],
};
